name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.25"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: uv run update.py

      - name: Commit & push changes
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@benkoppe.github.io"
          git config --global user.name "benkoppe/github-actions[bot]"
          git commit -m "Update README" -a || echo "No changes to commit"
          git push
